/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Third.glb 
*/

import React, {useEffect, useRef } from "react";
import { useGLTF, useTexture  } from "@react-three/drei";
import { convertMaterialsToBasic } from "../../utils/convertToBasic";
import * as THREE from 'three';
import { ContactShadows } from '@react-three/drei';

import { OBJExporter } from "../../ObjExporter";

import { clone } from '../../SkeletonUtils';

export const createMtl = (img) => {
  const textureLoader = new THREE.TextureLoader();
  const floorTexture = textureLoader.load(
    img,
    (tex) => {
      tex.encoding = THREE.sRGBEncoding; // để màu sắc chính xác
      // tex.anisotropy = Math.min(renderer.capabilities.getMaxAnisotropy(), 16); // tăng anisotropy cho texture sắc nét khi nghiêng
      tex.minFilter = THREE.LinearMipMapLinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.wrapS = THREE.RepeatWrapping;
      tex.wrapT = THREE.RepeatWrapping;
    },
    undefined,
    (err) => {
      console.error('Texture loading error:', err);
    }
  );
  return new THREE.MeshStandardMaterial({ map: floorTexture });
};


export const glassMaterial = new THREE.MeshPhysicalMaterial({
  color: 0xffffff,
  metalness: 0,
  roughness: 0,
  transmission: 1,       // tạo hiệu ứng trong suốt như kính
  thickness: 0.5,         // độ dày của kính
  clearcoat: 1,
  clearcoatRoughness: 0,
  reflectivity: 0.2,
  transparent: true,
  opacity: 1,
  envMapIntensity: 1,     // độ mạnh phản xạ môi trường
});

const glossyAluminumMaterial = new THREE.MeshPhysicalMaterial({
  color: 0x000,       // màu nhôm sáng xám
  metalness: 0.2,        // kim loại hoàn toàn
  roughness: 0.1,        // độ nhám thấp tạo bề mặt bóng cao
  clearcoat: 1.0,        // lớp phủ bóng cao
  clearcoatRoughness: 0, // lớp phủ cực bóng, không nhám
  reflectivity: 0.7,     // độ phản chiếu vật liệu
  envMapIntensity: 1.0,  // độ mạnh phản chiếu môi trường nếu có envMap
});

export default function Curtain({ uniqueKey = "curtain", ...props }) {
  
  const { nodes, materials, scene } = useGLTF('/models/NewRoom/curtain.glb');
  
  const clonedScene = React.useMemo(() => clone(scene), [scene]);
  // Gán lightmap cho từng mesh còn lại
  clonedScene.traverse((child) => {
    if (child.isMesh) {
      console.log(child);
      if (child.name === 'export_sample_bedroom_Curtain') {
        // Tạo material mới bóng với độ bóng cao (glossy)
        child.material = glossyAluminumMaterial;
        child.material.needsUpdate = true;
    
      }
    }
  });

  // exportOBJ();

  return (
  <group {...props} dispose={null}>
    <primitive key={`${uniqueKey}-scene`} object={clonedScene} scale={[1.45,1,1]} position={[0,0,0]} />
  </group>);

}
