/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Light_Third.glb 
*/

import React, {useEffect, useRef } from "react";
import { useGLTF, useTexture  } from "@react-three/drei";
import { convertMaterialsToBasic } from "../../utils/convertToBasic";
import * as THREE from 'three';
import { ContactShadows } from '@react-three/drei';

import { OBJExporter } from "../../ObjExporter";



export const createMtl = (img) => {
  const textureLoader = new THREE.TextureLoader();
  const floorTexture = textureLoader.load(
    img,
    (tex) => {
      tex.encoding = THREE.sRGBEncoding; // để màu sắc chính xác
      // tex.anisotropy = Math.min(renderer.capabilities.getMaxAnisotropy(), 16); // tăng anisotropy cho texture sắc nét khi nghiêng
      tex.minFilter = THREE.LinearMipMapLinearFilter;
      tex.magFilter = THREE.LinearFilter;
      tex.wrapS = THREE.RepeatWrapping;
      tex.wrapT = THREE.RepeatWrapping;
    },
    undefined,
    (err) => {
      console.error('Texture loading error:', err);
    }
  );
  return new THREE.MeshStandardMaterial({ map: floorTexture });
};


export const glassMaterial = new THREE.MeshPhysicalMaterial({
  color: 0xffffff,
  metalness: 0,
  roughness: 0,
  transmission: 1,       // tạo hiệu ứng trong suốt như kính
  thickness: 0.5,         // độ dày của kính
  clearcoat: 1,
  clearcoatRoughness: 0,
  reflectivity: 0.2,
  transparent: true,
  opacity: 1,
  envMapIntensity: 1,     // độ mạnh phản xạ môi trường
});

const glossyAluminumMaterial = new THREE.MeshPhysicalMaterial({
  color: 0xaaaaaa,       // màu nhôm sáng xám
  metalness: 0.2,        // kim loại hoàn toàn
  roughness: 0.1,        // độ nhám thấp tạo bề mặt bóng cao
  clearcoat: 1.0,        // lớp phủ bóng cao
  clearcoatRoughness: 0, // lớp phủ cực bóng, không nhám
  reflectivity: 0.7,     // độ phản chiếu vật liệu
  envMapIntensity: 1.0,  // độ mạnh phản chiếu môi trường nếu có envMap
});

export default function Model() {
  
  const exportOBJ = () => {
    const exporter = new OBJExporter();
    const result = exporter.parse(scene);
    const blob = new Blob([result], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'exported_model.obj';
    link.click();
  };


  // const { nodes, materials, scene } = useGLTF('/models/NewRoom/NewRoom.glb');
  // const lightMap = useTexture('/models/NewRoom/lightmap.png');
  // const { nodes, materials, scene } = useGLTF('/models/Light Room/dining_room-transformed.glb');
  const { nodes, materials, scene } = useGLTF('/models/Light Room/Light_Third.glb');
  const lightMap = useTexture('/models/NewRoom/living_room_lightmap_noncolor_1k.png');
  lightMap.flipY = false; // Quan trọng để ánh xạ UV đúng

  ["Frame_Pictures","Mirror","Plant_Leaves"].map(el=>
  {
  
    // Xóa mesh tên 'sofa' khỏi scene
    const meshToRemove = scene.getObjectByName(el);
    if (meshToRemove) {
      meshToRemove.geometry.dispose();
      if (Array.isArray(meshToRemove.material)) {
        meshToRemove.material.forEach(mat => mat.dispose());
      } else {
        meshToRemove.material.dispose();
      }
      meshToRemove.parent.remove(meshToRemove);
  }});

  
  // Gán lightmap cho từng mesh còn lại
  scene.traverse((child) => {
    if (child.isMesh) {
      console.log(child);
      // child.material.map = lightMap;
      // child.material.lightMap = lightMap;
      // child.material.lightMapIntensity = 1;
      // child.material.needsUpdate = true;
    }
  });

  // exportOBJ();

  return <primitive object={scene} />;
}

// useGLTF.preload("/models/Light Room/Light_Third.glb");
// useGLTF.preload("/models/Light Room/obj/Bed.glb");
// useGLTF.preload("/models/Light Room/obj/Bedtab.glb");
// useGLTF.preload("/models/Light Room/obj/Bench.glb");
// useGLTF.preload("/models/Light Room/obj/direction.glb");
// useGLTF.preload("/models/Light Room/obj/WorkTable.glb");
// useGLTF.preload("/models/Light Room/obj/Readchair.glb");
// useGLTF.preload("/models/Light Room/obj/Wardrobe1m2.glb");
// useGLTF.preload("/models/Light Room/obj/Wardrobe2m4.glb");
// useGLTF.preload("/models/Light Room/obj/Wardrobe3m6.glb");